version: '3.9'

services:
  app:
    build:
      context: "./"
      dockerfile: "flask_Dockerfile"
    networks:
      - Regain-network
    ports:
      - "5080:80"
      - "443:443"
    container_name: Regain-app
    volumes:
      - ./app:/usr/src/app
      - /etc/letsencrypt:/etc/letsencrypt

  db:
    build:
      context: "./"
      dockerfile: "mariadb_Dockerfile"
    networks:
      - Regain-network
    ports:
      - "3306:3306"
    container_name: Regain-db
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "regain@team24"

networks:
  Regain-network:
